replicaCount: 1

image:
  repository: crossfil/aiops-quality-project  
  tag: latest                                 
  pullPolicy: Always                          

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
