apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aiops-prometheus
  namespace: monitoring
spec:
  serviceMonitorNamespaceSelector: {} 
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
